[package]
name = "touying-hust"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "lib.typ"
repository = "https://github.com/btmxh/touying-hust"
authors = ["btmxh"]
license = "MIT-0"
description = "touying template for HUST slides (i will NOT use powerpoint)"
keywords = ["touying", "hust"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
